[package]
name = "eren_2d"
version = "0.1.0"
edition = "2024"

[dependencies]
eren_core = { path = "../eren_rs_core" }
pollster = "0.4.0"
tokio = { version = "1.45", features = ["rt-multi-thread", "macros", "sync"] }
wgpu = "25.0.0"
winit = "0.30.11"
